# config.yml (simplified version)
language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
- name: EntitySynonymMapper

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: TEDPolicy
assistant_id: 20250301-060109-right-patio
